amazon:
  aws:
    account: 377704527648
    access-key: "AKIAVP4HRW4QFUK4KC4O"
    secret-key: "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"
    dynamodb:
      endpoint: https://dynamodb.sa-east-1.amazonaws.com/
      region: sa-east-1

api-artist:
  artist: "http://localhost:8091"



logging:
  level:
    root: debug